#!/usr/bin/env bash
DIRECTORY=$1
BINARY_NAME=$2
shift 2

pushd $DIRECTORY>/dev/null

export SHELL=bash
export RESTARTER_ARGS="$@"
export RUST_BACKTRACE=1

while true; do ls src/*.rs *.toml | entr -d -s 'cargo build && '$(dirname "${BASH_SOURCE[0]}")'/cargo_restarter '$BINARY_NAME' ${RESTARTER_ARGS}'; done
popd>/dev/null
pkill $BINARY_NAME 2>/dev/null
